services:
  - type: web
    name: youtube-converter-web
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app import init_db; init_db()"
    startCommand: gunicorn app:app -k gevent -b 0.0.0.0:$PORT
    envVars:
      - key: PGDATABASE
        fromDatabase:
          name: youtube-converter-db
          property: database
      - key: PGUSER
        fromDatabase:
          name: youtube-converter-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: youtube-converter-db
          property: password
      - key: PGHOST
        fromDatabase:
          name: youtube-converter-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: youtube-converter-db
          property: port
      - key: REDIS_URL
        fromService:
          type: redis
          name: youtube-converter-redis
          property: connectionString
      - key: AWS_ACCESS_KEY_ID
        value: your-aws-key
      - key: AWS_SECRET_ACCESS_KEY
        value: your-aws-secret
      - key: S3_BUCKET
        value: your-bucket-name
      - key: ADMIN_USER
        value: your-admin-user
      - key: ADMIN_PASSWORD
        value: your-admin-password

  - type: worker
    name: celery-worker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A tasks worker --loglevel=info
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: youtube-converter-redis
          property: connectionString
      - key: AWS_ACCESS_KEY_ID
        value: your-aws-key
      - key: AWS_SECRET_ACCESS_KEY
        value: your-aws-secret
      - key: S3_BUCKET
        value: your-bucket-name

databases:
  - name: youtube-converter-db
    databaseName: youtube_conv
    user: yt_admin
    plan: free

redis:
  - name: youtube-converter-redis
    plan: free
